# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fdetect/pbgen/safe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x66\x64\x65tect/pbgen/safe.proto\x12\nfdetect.pb\"(\n\x07OpError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x05Image\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\"%\n\x04Rect\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"[\n\x11\x46\x61\x63\x65\x44\x65tectRequest\x12\x0b\n\x03rid\x18\x01 \x01(\t\x12\x16\n\x0ereturnEncoding\x18\x02 \x01(\x08\x12!\n\x06images\x18\x04 \x03(\x0b\x32\x11.fdetect.pb.Image\" \n\x04\x46\x61\x63\x65\x12\x0b\n\x03loc\x18\x01 \x03(\x05\x12\x0b\n\x03\x65nc\x18\x02 \x03(\x02\"S\n\x0f\x44\x65tectionResult\x12\x10\n\x08numFaces\x18\x01 \x01(\x05\x12\x1f\n\x05\x66\x61\x63\x65s\x18\x02 \x03(\x0b\x32\x10.fdetect.pb.Face\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"\x8a\x01\n\x12\x46\x61\x63\x65\x44\x65tectResponse\x12\"\n\x06status\x18\x01 \x01(\x0e\x32\x12.fdetect.pb.Status\x12\"\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x13.fdetect.pb.OpError\x12,\n\x07results\x18\x03 \x03(\x0b\x32\x1b.fdetect.pb.DetectionResult\"0\n\rHealthRequest\x12\x11\n\tRequestId\x18\x01 \x01(\t\x12\x0c\n\x04\x46ull\x18\x02 \x01(\x08\" \n\x0eHealthResponse\x12\x0e\n\x06Status\x18\x01 \x01(\t*\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01*\x1f\n\x0b\x44\x65tectModel\x12\x07\n\x03HOG\x10\x00\x12\x07\n\x03\x43NN\x10\x01*4\n\rEncodingModel\x12\r\n\tEM_NOTSET\x10\x00\x12\t\n\x05SMALL\x10\x01\x12\t\n\x05LARGE\x10\x02\x32U\n\nFaceDetect\x12G\n\x06\x44\x65tect\x12\x1d.fdetect.pb.FaceDetectRequest\x1a\x1e.fdetect.pb.FaceDetectResponse2F\n\x06Health\x12<\n\x03get\x12\x19.fdetect.pb.HealthRequest\x1a\x1a.fdetect.pb.HealthResponseb\x06proto3')

_STATUS = DESCRIPTOR.enum_types_by_name['Status']
Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
_DETECTMODEL = DESCRIPTOR.enum_types_by_name['DetectModel']
DetectModel = enum_type_wrapper.EnumTypeWrapper(_DETECTMODEL)
_ENCODINGMODEL = DESCRIPTOR.enum_types_by_name['EncodingModel']
EncodingModel = enum_type_wrapper.EnumTypeWrapper(_ENCODINGMODEL)
OK = 0
ERROR = 1
HOG = 0
CNN = 1
EM_NOTSET = 0
SMALL = 1
LARGE = 2


_OPERROR = DESCRIPTOR.message_types_by_name['OpError']
_IMAGE = DESCRIPTOR.message_types_by_name['Image']
_RECT = DESCRIPTOR.message_types_by_name['Rect']
_FACEDETECTREQUEST = DESCRIPTOR.message_types_by_name['FaceDetectRequest']
_FACE = DESCRIPTOR.message_types_by_name['Face']
_DETECTIONRESULT = DESCRIPTOR.message_types_by_name['DetectionResult']
_FACEDETECTRESPONSE = DESCRIPTOR.message_types_by_name['FaceDetectResponse']
_HEALTHREQUEST = DESCRIPTOR.message_types_by_name['HealthRequest']
_HEALTHRESPONSE = DESCRIPTOR.message_types_by_name['HealthResponse']
OpError = _reflection.GeneratedProtocolMessageType('OpError', (_message.Message,), {
  'DESCRIPTOR' : _OPERROR,
  '__module__' : 'fdetect.pbgen.safe_pb2'
  # @@protoc_insertion_point(class_scope:fdetect.pb.OpError)
  })
_sym_db.RegisterMessage(OpError)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'fdetect.pbgen.safe_pb2'
  # @@protoc_insertion_point(class_scope:fdetect.pb.Image)
  })
_sym_db.RegisterMessage(Image)

Rect = _reflection.GeneratedProtocolMessageType('Rect', (_message.Message,), {
  'DESCRIPTOR' : _RECT,
  '__module__' : 'fdetect.pbgen.safe_pb2'
  # @@protoc_insertion_point(class_scope:fdetect.pb.Rect)
  })
_sym_db.RegisterMessage(Rect)

FaceDetectRequest = _reflection.GeneratedProtocolMessageType('FaceDetectRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACEDETECTREQUEST,
  '__module__' : 'fdetect.pbgen.safe_pb2'
  # @@protoc_insertion_point(class_scope:fdetect.pb.FaceDetectRequest)
  })
_sym_db.RegisterMessage(FaceDetectRequest)

Face = _reflection.GeneratedProtocolMessageType('Face', (_message.Message,), {
  'DESCRIPTOR' : _FACE,
  '__module__' : 'fdetect.pbgen.safe_pb2'
  # @@protoc_insertion_point(class_scope:fdetect.pb.Face)
  })
_sym_db.RegisterMessage(Face)

DetectionResult = _reflection.GeneratedProtocolMessageType('DetectionResult', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONRESULT,
  '__module__' : 'fdetect.pbgen.safe_pb2'
  # @@protoc_insertion_point(class_scope:fdetect.pb.DetectionResult)
  })
_sym_db.RegisterMessage(DetectionResult)

FaceDetectResponse = _reflection.GeneratedProtocolMessageType('FaceDetectResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACEDETECTRESPONSE,
  '__module__' : 'fdetect.pbgen.safe_pb2'
  # @@protoc_insertion_point(class_scope:fdetect.pb.FaceDetectResponse)
  })
_sym_db.RegisterMessage(FaceDetectResponse)

HealthRequest = _reflection.GeneratedProtocolMessageType('HealthRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHREQUEST,
  '__module__' : 'fdetect.pbgen.safe_pb2'
  # @@protoc_insertion_point(class_scope:fdetect.pb.HealthRequest)
  })
_sym_db.RegisterMessage(HealthRequest)

HealthResponse = _reflection.GeneratedProtocolMessageType('HealthResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHRESPONSE,
  '__module__' : 'fdetect.pbgen.safe_pb2'
  # @@protoc_insertion_point(class_scope:fdetect.pb.HealthResponse)
  })
_sym_db.RegisterMessage(HealthResponse)

_FACEDETECT = DESCRIPTOR.services_by_name['FaceDetect']
_HEALTH = DESCRIPTOR.services_by_name['Health']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=594
  _STATUS._serialized_end=621
  _DETECTMODEL._serialized_start=623
  _DETECTMODEL._serialized_end=654
  _ENCODINGMODEL._serialized_start=656
  _ENCODINGMODEL._serialized_end=708
  _OPERROR._serialized_start=40
  _OPERROR._serialized_end=80
  _IMAGE._serialized_start=82
  _IMAGE._serialized_end=116
  _RECT._serialized_start=118
  _RECT._serialized_end=155
  _FACEDETECTREQUEST._serialized_start=157
  _FACEDETECTREQUEST._serialized_end=248
  _FACE._serialized_start=250
  _FACE._serialized_end=282
  _DETECTIONRESULT._serialized_start=284
  _DETECTIONRESULT._serialized_end=367
  _FACEDETECTRESPONSE._serialized_start=370
  _FACEDETECTRESPONSE._serialized_end=508
  _HEALTHREQUEST._serialized_start=510
  _HEALTHREQUEST._serialized_end=558
  _HEALTHRESPONSE._serialized_start=560
  _HEALTHRESPONSE._serialized_end=592
  _FACEDETECT._serialized_start=710
  _FACEDETECT._serialized_end=795
  _HEALTH._serialized_start=797
  _HEALTH._serialized_end=867
# @@protoc_insertion_point(module_scope)
